#  Python & NumPy – Question Paper (50 Marks)

### Section A – Multiple Choice Questions

(10 × 1 = 10 Marks)

(Answer all questions)

1. Which of the following is used to install NumPy in Python?

a) import numpy

✅b) pip install numpy

c) NumPy.install()

d) python -numpy

2. What is the default data type of NumPy array elements if not specified?

✅a) float64

b) int64

c) object

d) string

3. Which method is used to find the shape of a NumPy array?

a) arr.size

b) arr.ndim

✅c) arr.shape

d) arr.length()

4. Which of the following is not a feature of NumPy?

a) Broadcasting

b) Fast mathematical operations

✅c) Database connectivity

d) Multidimensional arrays


5. In Python, which keyword is used to define a function?

a) func

b) define

✅c) def

d) function

6. Which NumPy function is used to generate an array of evenly spaced numbers?

a) numpy.linspace()

b) numpy.arange()


✅c) Both (a) and (b)

d) None of these


7. What will np.eye(3) produce?

✅a) Identity matrix of order 3

b) 3 × 3 matrix of zeros

c) 3 × 3 diagonal matrix with all elements = 3

d) Error


8. Which operator is used for element-wise multiplication in NumPy arrays?

✅a) *

b) @

c) .dot()

d) /

9. In Python, which of the following is a mutable data type?

a) Tuple

b) String

✅c) List

d) Integer

10. Which function converts a Python list into a NumPy array?

a) np.asarray()

b) np.convert()

c) np.arraylist()

✅d) np.array()



### Section B - Short Notes

(2 x 5 = 10 Marks)

(Answer any two)

1. Explain broadcasting in NumPy with an example.

Broadcasting is the ability of NumPy to perform operations on arrays of different shapes. Smaller arrays are stretched to match the shape of the larger array without actually copying data.

In [15]:
import numpy as np
a = np.array([1, 2, 3])
b = 2
print(a + b)   # [3 4 5]


[3 4 5]


Here, 2 is broadcasted to [2, 2, 2].

2. Difference between Python lists and NumPy arrays.

| Feature    | Python List               | NumPy Array                        |
| ---------- | ------------------------- | ---------------------------------- |
| Data type  | Can store different types | Stores only one type (homogeneous) |
| Speed      | Slower                    | Much faster (C-based)              |
| Operations | Element by element        | Vectorized, element-wise           |
| Memory     | Higher                    | Lower, more efficient              |


3. Slicing in NumPy arrays with examples.

Slicing allows extracting parts of an array.

In [16]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])     # [20 30 40]
print(arr[:3])      # [10 20 30]
print(arr[::2])     # [10 30 50]

[20 30 40]
[10 20 30]
[10 30 50]


4. Python functions with default arguments.

Default arguments allow parameters to have default values.

In [17]:
def greet(name="User"):
    print("Hello", name)

greet()       # Hello User
greet("Krish") # Hello Krish


Hello User
Hello Krish


5. NumPy statistical functions (mean, median, std).

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))   # 3.0
print(np.median(arr)) # 3.0
print(np.std(arr))    # 1.4142

3.0
3.0
1.4142135623730951


### Section C – Descriptive Questions

1. Create a NumPy array of size 10 filled with zeros.

In [19]:
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Reverse a list without using built-in reverse.

In [20]:
lst = [1, 2, 3, 4, 5]
print(lst[::-1])

[5, 4, 3, 2, 1]


3. Generate a 1D NumPy array of numbers from 10 to 50 with step size 5.

In [21]:
arr = np.arange(10, 51, 5)
print(arr)  # [10 15 20 25 30 35 40 45 50]

[10 15 20 25 30 35 40 45 50]


4. Difference between np.zeros() and np.ones().

* np.zeros(n) → array filled with 0s

* np.ones(n) → array filled with 1s

In [22]:
print(np.zeros(3)) # [0. 0. 0.]
print(np.ones(3))  # [1. 1. 1.]


[0. 0. 0.]
[1. 1. 1.]


5. Python function to check if a number is prime.

In [23]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

print(is_prime(7))  # True


True


6. Difference between arr.reshape() and arr.resize().

* reshape() → returns a new array with the given shape (does not modify original).

* resize() → modifies the original array in place.

7. NumPy code to create a 3×3 identity matrix, and arr.ravel().

In [24]:
arr = np.eye(3)
print(arr)

a = np.array([[1,2],[3,4]])
print(a.ravel())   # [1 2 3 4]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 2 3 4]


8. Difference between arr.flatten() and arr.ravel().

* flatten() → returns a copy of the array.

* ravel() → returns a view (changes affect original).

In [25]:
a = np.array([[1,2],[3,4]])
print(a.flatten())  # [1 2 3 4] (copy)
print(a.ravel())    # [1 2 3 4] (view)

[1 2 3 4]
[1 2 3 4]


9. Python code to swap two variables without using a temporary variable.

In [26]:
a, b = 5, 10
a, b = b, a
print(a, b)  # 10 5

10 5


10. Create two 2D arrays and perform matrix multiplication using NumPy.

In [27]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]
